version: '3'

services:

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: N1LIE691Gd4R1qdnQ1tX5YzWAJsaziAHg8dwx
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
